### ISSUE TITLE
Does not work seem to work with newer versions of sveltekit

### ISSUE THREAD

**Issue by everdrone** [geoffrich/sveltekit-shared-element-transitions#1]
Broken for me with `@sveltejs/kit` `^1.20.4` and `svelte` `^4.0.5`.

Maybe I'm missing something but it only transitions when using the back/forward navigation buttons in the browser, not when visiting `<a>` elements

- tested on Chrome `116.0.5845.110` both on Windows 11 and macOS 13.5
- repo: https://github.com/everdrone/sveltekit-view-transition-problem

**Comment by geoffrich** [comment]
This should work now with the new `onNavigate` lifecycle hook introduced in SvelteKit 1.24: https://github.com/geoffrich/sveltekit-view-transitions/commit/21b0173cfcce13e08f77f2e38afc3440b76da77e

Deployed version: https://sveltekit-shared-element-transitions-codelab.vercel.app/

Docs: https://kit.svelte.dev/docs/modules#$app-navigation-onnavigate
